### ISSUE TITLE
New Maintainer?

### ISSUE THREAD

**Issue by vordimous** [newTendermint/awesome-bigdata#339]
Is this repo still being maintained?

**Comment by vordimous** [comment]
@newTendermint @hslatman Do you know if anyone is keeping this repo updated

**Comment by hslatman** [comment]
It worked 😄 Thanks for contributing https://github.com/newTendermint/awesome-bigdata/pull/338. Interesting tool, too.

**Comment by vordimous** [comment]
Thank you, @hslatman! I have been working to improve the awesome-kafka repo as well. This repo has so much good info I was hoping it didn't go dormant :)
